### ISSUE TITLE
CNN explanation and pre-processing

### ISSUE THREAD

**Issue by mariafranciscva496** [lusx2000/CNN-for-P300#1]
Hello, could you explain better the type of CNN that you used? by any chance was the one reference in this paper : "Convolutional Neural Networks for P300 Detection with Application to Brain-Computer Interfaces by Hubert Cecotti and Axel Gra¨ser" ?? 

And how do you pre-process the data from the BCI competition dataset? what files do you use?

many thanks 👍

**Comment by omoiFly** [comment]
Sorry for so long to reply you, This is a curriculum project which my teacher have already do some preprocess for us on the original dataset i don't know. I just calc the mean of five experiments for each subject and put all 64 channel to the CNN model. the processed data(MATLAB data file) you can found the download link in the readme.md.

Actually I didn't refer the paper. The model i created just a vanilla CNN similar to LeNet. you can check in the Model.py file.
